### ISSUE TITLE
Retrieving past transactions using webcoin?

### ISSUE THREAD

**Issue by paulkernfeld** [mappum/webcoin#11]
I'm interested in retrieving past transactions for a particular address using webcoin. As far as I know, the Bitcoin protocol doesn't provide a way to ask for all the transactions for an address, but if you have a list of blocks that may contain transactions for the address, then as long as your Bloom filter is set, you should be able to request those blocks and receive the relevant transactions.

Is this something that can currently be done with webcoin? If not, could I try to add this feature?

**Comment by mappum** [comment]
You actually don't need to know specific blocks, just the creation date of the wallet. Then from there, you can scan all blocks up to the most recent one looking for relevant transactions with the bloom filter. This is possible in wallet.js, but it is untested and the API may be subject to change.

**Comment by paulkernfeld** [comment]
Oh… cool! That’s way easier than I thought! So, is `wallet.state.createdAt` the property that I would need to set in that case?

**Comment by mappum** [comment]
>Oh… cool! That’s way easier than I thought! So, is `wallet.state.createdAt` the property that I would need to set in that case?

You shouldn't have to set it manually, that is designed so when you create a new wallet the `createdAt` timestamp gets set for you. But I suppose we would want to make it configurable for importing preexisting wallets.

**Comment by paulkernfeld** [comment]
All right, I was previously confused about how the `from` argument worked for `createTransactionStream`. But now I understand. Anyways, I got it working and made a simple burn verification library: https://github.com/paulkernfeld/burnie Thanks for your help!
