### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of null

### ISSUE THREAD

**Issue by paulkernfeld** [mappum/webcoin#16]
I got this error on the following line of code, `lib/node.js` line 160 or so, presumably because `err` is null. I saw this while running a browserified version of `bin/wallet.js`.

```
if (err !== true && !(err.message === 'Database is not open' && self.closing)) {
```

I'm happy to send a PR to fix this, but I'm a little confused by the way the `err` variable is working. What does `err = true` mean here? It sort of seems like `err = true` isn't actually an error.

**Comment by mappum** [comment]
The current `Node` code is being replaced, so this error shouldn't be relevant anymore.

But just to to answer your question, I was setting the `err` to `true` as a way to break execution from async tasks (using the `async` module), since the tasks stop executing on the first error).
