### ISSUE TITLE
decred module support

### ISSUE THREAD

**Issue by raedah** [mappum/webcoin#25]
Just to start off the conversation, I would like a module for decred.

**Comment by mappum** [comment]
You can create a module containing the params for any currency, see the
[`webcoin-bitcoin`](https://github.com/mappum/webcoin-bitcoin)
and [`webcoin-bitcoin-testnet`](
https://github.com/mappum/webcoin-bitcoin-testnet) modules for some
examples.

**Comment by mappum** [comment]
You can create a module containing the params for any currency, see the [`webcoin-bitcoin`](https://github.com/mappum/webcoin-bitcoin) and [`webcoin-bitcoin-testnet`](https://github.com/mappum/webcoin-bitcoin-testnet) modules for some examples.

**Comment by mappum** [comment]
Closing the issue since this isn't a webcoin issue.
