### ISSUE TITLE
I think this project need a api-doc

### ISSUE THREAD

**Issue by soliury** [mappum/webcoin#3]
Good job, 
This is a nice project, But I find that there are no api-doc. Can you write a api-doc?

**Comment by mappum** [comment]
Yes, there will be a lot of documentation soon. I am currently breaking out the codebase into smaller modules, which are each getting detailed docs. I will comment in this issue when most of the big components are documented. :smile:

**Comment by soliury** [comment]
And I have a question:

 Can you make the module support browser , node.js and react-native at the same time?


I know that now it support browser and node.js, but I think you can also support the react-native.  You can consider this project : https://github.com/oney/react-native-webrtc

**Comment by mappum** [comment]
Sure, I'll keep React Native in mind and ensure compatibility. Thanks for letting me know about that module :+1:

**Comment by soliury** [comment]
Ok, When you finish , I am considering using this module to build a react-native app for bitcoin.  I am waiting for your new module. :+1:

**Comment by paulkernfeld** [comment]
@mappum can I help at all with refactoring or documenting? I think I could figure out Webcoin enough to write some simple documentation.

**Comment by mappum** [comment]
@paulkernfeld Sure! It would be helpful if you browse the repos listed in the README and make sure the documentation I have written so far is clear enough. Beyond that, you could join #webcoin on Freenode to discuss the refactoring.

**Comment by xloem** [comment]
Have you guys considered supporting the https://github.com/blockai/abstract-common-blockchain and https://github.com/blockai/abstract-common-wallet APIs?  This might additionally ease documentation and interface choices.

**Comment by mappum** [comment]
@xloem I've seen those and that are a good idea. We could easily make a
module that wraps the Webcoin API to provide the common-X APIs.

**Comment by mappum** [comment]
Webcoin has now been broken up into modules, each with their own documentation. See the README for a list.

**Comment by soliury** [comment]
good job
