### ISSUE TITLE
Is it working ?

### ISSUE THREAD

**Issue by rllola** [mappum/webcoin#43]
Is it working ? 
I can't get it to sync. It seems it is not able to find peers...

**Comment by mappum** [comment]
The seed server's SSL certificate had expired so I renewed it. Let me know if it's still not syncing.

**Comment by rllola** [comment]
I should have precise that I am on testnet.

**Comment by mappum** [comment]
It should work on testnet, I just tried this script in Node (although it should also work in the browser): https://gist.github.com/mappum/789a6dab3a4b155851f8ac56ef369506

**Comment by rllola** [comment]
Ok I have figured out my mistake. When ready is emit it means it is ready to download chain. My bad.
