### ISSUE TITLE
Default web seed doesn't work

### ISSUE THREAD

**Issue by paulkernfeld** [mappum/webcoin#5]
I'm not able to make a connection to 104.236.185.38:8192 from my computer.

```
paul ~/repos/webcoin master $ node bin/bridge.js
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 104.236.185.38:8192
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
```

**Comment by mappum** [comment]
I restarted the server, it should work now. Let me know if you still have trouble connecting.

**Comment by paulkernfeld** [comment]
The web seed seems to have gone down again. Have you had any thoughts about ways to make the system more robust? Would it help if I launched my own web seed server?
